### ISSUE TITLE
Создать модуль с входными и выходными данными для расчета цилиндрических передач

### ISSUE THREAD

**Issue by DennisMorosoff** [pisfu/SpurGear#1]
Откройте файл Testing/GearTypesUnit.pas там представлен образец оформления модуля с входными и выходными данными вашего проекта (данные оформляются в виде записи)
Список параметров можно найти в файле TCAD23/COGWHEEL.PAS (осторожно DOS-кодировка)
Создайте аналогичный модуль с входным и выходным потоком для цилиндрической передачи
Создайте пустой проект вашей будущей работы, добавьте в этот проект созданный файл
Залейте проект на свой репозиторий

**Comment by EvgenyKuksov** [comment]
Денис Иванович, проверьте пожалуйста unit с входными и выходными параметрами, называется "Data".

**Comment by DennisMorosoff** [comment]
Да, вроде компилится
